# Generated by Django 4.1 on 2022-08-28 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas_2', '0007_fonte_credito'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Credito',
        ),
    ]
