# Generated by Django 4.1 on 2022-08-29 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contas_2', '0008_delete_credito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('descrição', models.CharField(max_length=200)),
                ('observações', models.TextField(blank=True, null=True)),
                ('data', models.DateTimeField()),
                ('fonte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas_2.fonte')),
            ],
            options={
                'verbose_name_plural': 'Créditos',
            },
        ),
    ]
